sha3 functions: initial
w3c/sparql-dev pull request #183
Opened 2023-04-13 21:18 UTC by domel

2023-04-14 18:02 UTC, TallTed requested changes

2023-04-14 18:02 UTC, TallTed commented on SEP/SEP-0008/sep-0008.md
> +SHA-3 (Secure Hash Algorithm 3) is the member of the Secure Hash Algorithm family of standards, released by NIST on August 5, 2015. This document presents a set of SHA-3 functions in SPARQL.
```suggestion
SHA-3 (Secure Hash Algorithm 3) is a member of the Secure Hash Algorithm family of standards, released by NIST on August 5, 2015. This document presents a set of SHA-3 functions in SPARQL.
```

2023-04-14 18:02 UTC, TallTed commented on SEP/SEP-0008/sep-0008.md
> +SPARQL was published in 2013. In 2015 a new set of SHA-3 functions appeared. The SHA-3 functions have several benefits:
```suggestion
SPARQL was published in 2013. In 2015, a new set of SHA-3 functions appeared. The SHA-3 functions have several benefits:
```

2023-04-14 18:02 UTC, TallTed commented on SEP/SEP-0008/sep-0008.md
> +* Future-proofing: SHA-3 functions were designed with the future in mind, and they have a long projected lifespan. They are resistant to quantum computing attacks, making them an excellent choice for
```suggestion
* **Security:** SHA-3 functions provide a high level of security against various types of attacks such as pre-image, collision, and length extension attacks. 
* **Popularity:** SHA-3 functions are widely used.
* **Efficiency:** SHA-3 functions are optimized for performance and can be implemented efficiently in software. They are designed to be faster and more efficient than their predecessors, such as SHA-1 and SHA-2.
* **Standardization:** SHA-3 functions are standardized by NIST and have been extensively reviewed by the cryptographic community. 
* **Future-proofing:** SHA-3 functions were designed with the future in mind, and they have a long projected lifespan. They are resistant to quantum computing attacks, making them an excellent choice for long-term security needs.
```

2023-04-14 18:02 UTC, TallTed commented on SEP/SEP-0008/sep-0008.md
> +
```suggestion
```

2023-09-15 10:30 UTC, TallTed approved these changes

2023-10-09 11:13 UTC, JervenBolleman commented
Looks good to me. Could the section be extended with examples as in [the hash section](https://www.w3.org/TR/sparql11-query/#func-hash) of the current spec?

2024-06-11 08:35 UTC, afs approved these changes

2024-06-11 08:37 UTC, merged